version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
    restart: unless-stopped
    networks:
      - movie-verse-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - movie-verse-network
    x-google-cloudrun:
      ingress-container: true

networks:
  movie-verse-network:
    driver: bridge

volumes:
  backend_data:
